ch-setup-react-project-#181414550
atlp-rwanda/cod-fe pull request #1
Opened 2022-05-06 09:15 UTC by SergeNm

## What does this PR do?
- Set up an empty react project

## Description of task
- The team should create a react project from scratch using Webpack 4, Babel, and the Airbnb linting option.

## How to test this PR?
- install nodejs and **yarn** package manager
- run **yarn install**
- run "npm run "**eslint-fix**" to see eslint working
- then run "**yarn run dev**"

2022-05-09 10:28 UTC, rukundo-kevin requested changes

2022-05-09 10:28 UTC, rukundo-kevin commented on src/index.js
> +ReactDOM.render(<App />, document.getElementById('app'));
ReactDOM.render is no longer supported in React 18. Use createRoot instead
```suggestion
const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(
    <App />
)

2022-05-09 11:10 UTC, rukundo-kevin requested changes

2022-05-09 11:10 UTC, rukundo-kevin commented on src/index.html
> +    <title>React, Webpack, Babel Starter Pack</title>
Change the title, This won't always be a starter pack

2022-05-09 15:30 UTC, NNesta requested changes

2022-05-09 15:30 UTC, NNesta commented on webpack.config.js
> +  entry: path.join(__dirname, 'src', 'index.js'),
use es6

2022-05-10 14:34 UTC, iyaremye-faustin commented on src/components/app.js
> +export default App;
Change app.js to App.js (Good practice for components naming)

2022-05-10 14:35 UTC, iyaremye-faustin reviewed
Good work

2022-05-10 15:14 UTC, rukundo-kevin approved these changes

2022-05-10 15:15 UTC, NNesta approved these changes
Good job

2022-05-10 16:28 UTC, merged