reset-password-#181414561
atlp-rwanda/cod-fe pull request #15
Opened 2022-05-24 14:33 UTC by iyaremye-faustin

# 1. Name of task
- User should be given a reset password link
# 2. Pivot Tracker ID
-[ #181414561](https://www.pivotaltracker.com/story/show/181414561)

# 3. Branch Name
- ft-reset-password-181414561
# 4. Description of task
Registers users should be able to reset forgotten
# 5. How can PR be tested.
Given that the app is running in,
- (/password/reset) takes to the reset password page to enter his/her email

2022-06-01 05:12 UTC, rukundo-kevin requested changes
Write tests for the this.

2022-06-01 05:12 UTC, rukundo-kevin commented on src/api/passwordApi.js
> +  }
Don't redefine the error message as the backend server will appropriate error message. DRY

2022-06-01 05:12 UTC, rukundo-kevin commented on src/api/passwordApi.js
> +  }
DRY

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/NewPassword.js
> +          />
Use the input component instead of using plain HTML.

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/NewPassword.js
> +          />
Use the input component instead of using plain HTML.

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/NewPassword.js
> +          </button>
Use the button component

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/NewPassword.js
> +          </button>
Use the button component

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/NewPassword.js
> +          />
Use the input component instead of using plain HTML.

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/ResetPassword.js
> +      />
Use Input component

2022-06-01 05:12 UTC, rukundo-kevin commented on src/components/password/ResetPassword.js
> +      </button>
use button component

2022-06-07 07:46 UTC, mucyoalexaxel approved these changes
LGTM

2022-06-07 07:48 UTC, mucyoalexaxel requested changes
Good Work @iyaremye-faustin. PR need a rebase

2022-06-07 07:52 UTC, rukundo-kevin requested changes
Add link to login component on 'forgot password' to link reset password form with login and change Reset password color from coral to yellow which we use.

2022-06-07 10:06 UTC, rukundo-kevin approved these changes

2022-06-07 14:01 UTC, merged