#181414562 Feat: User login
atlp-rwanda/cod-fe pull request #16
Opened 2022-05-24 16:05 UTC by rukundo-kevin

# 1. Name of task
- Implement Signup/Register 
# 2. Pivot Tracker ID
-[ #181414562](https://www.pivotaltracker.com/story/show/181414562)

# 3. Branch Name
- `ft-register-181414562 `
# 4. Description of task
**Why**
To be able to use the application and access authenticated routes, a login form should be presented to users.

**Acceptance Criteria**

**GIVEN** user successfully logs in.
**WHEN** user passes appropriate login parameters 
**THEN** user should be able to login.
# Screenshots

<img width="609" alt="Screen Shot 2022-05-30 at 15 23 43" src="https://user-images.githubusercontent.com/38954786/171001430-cd5c7135-2c39-4ebc-bb85-afc9a5ab1b1f.png">

## When there is an error
<img width="591" alt="Screen Shot 2022-05-30 at 15 34 47" src="https://user-images.githubusercontent.com/38954786/171003871-b793228f-1ae9-49af-989e-73acf9a38a10.png">

# 5 How can PR be tested.

Navigate to the terminal and start the server,
- go to the login route on your browser.
- Change the baseURL in `src/api/index.js`
- Go to the browser and you are ready to test the server

2022-05-27 05:56 UTC, NNesta requested changes

2022-05-27 05:56 UTC, NNesta commented on src/api/userApi.js
>  });
Please use the hosted url

2022-05-27 10:56 UTC, NNesta requested changes

2022-05-27 10:56 UTC, NNesta commented on src/routes/index.js
>        <Route path="/dummy" element={<App />} />
remove or rename this route it is colliding with Homeuser dashboard below

2022-05-27 11:19 UTC, mucyoalexaxel approved these changes, later dismissed
LGTM

2022-05-27 11:20 UTC, NNesta approved these changes, later dismissed
Nice work

2022-05-30 11:30 UTC, iyaremye-faustin approved these changes
Good work

2022-05-30 12:15 UTC, NNesta approved these changes
Good Job

2022-05-30 16:01 UTC, EmyRukundo approved these changes

2022-05-30 16:02 UTC, merged