feat (Reject trip request) #181414569
atlp-rwanda/cod-fe pull request #18
Opened 2022-05-30 09:02 UTC by NNesta

# 1. Name of task
- Reject Request (By Requester’s Manager) UI
# 2. Pivot Tracker ID
-[ #181414564](https://www.pivotaltracker.com/story/show/181414569)

# 3. Branch Name
- ft-Reject-Request-##181414569
# 4. Description of task
In some cases, travel requests will not be allowed to proceed to the next phase

**As a manager**, I should be able to reject a request created by my direct report
**So that**, my direct report’s travel request can be aborted

## **Acceptance Criteria**
- Manager is able to reject request
- Status of the approved request changes to ‘Rejected’
- Request owner can see the status of the rejected request as ‘Rejected’
# 5. How can PR be tested.
Given that the user is logged in,
- (/dashboard) click on more button then will rediredt you to /approval page where you can get button of rejecting
** User Interface on the page**
<img width="697" alt="Screen Shot 2022-05-19 at 09 25 02" src="https://user-images.githubusercontent.com/74612176/171153897-53319340-2517-44f5-aa2c-65599548a3cf.png">

2022-05-31 16:17 UTC, mucyoalexaxel requested changes, later dismissed
@NNesta  remove `src/.DS_Store`

2022-06-01 07:49 UTC, NNesta commented
> @NNesta remove `src/.DS_Store`

That is what I did

2022-06-01 15:55 UTC, EmyRukundo requested changes

2022-06-01 15:55 UTC, EmyRukundo commented on test/mocks/handlers/approve.handler.js
> +      ctx.status(201),
wrong status code

2022-06-02 13:25 UTC, NNesta commented on test/mocks/handlers/approve.handler.js
> +      ctx.status(201),
Correected

2022-06-02 13:25 UTC, NNesta commented on test/mocks/handlers/approve.handler.js
> +      ctx.status(201),
Correected

2022-06-02 13:26 UTC, SergeNm requested changes, later dismissed

2022-06-02 13:26 UTC, SergeNm commented on src/components/tables/ApprovalComponent.js
>  }
prefer refactoring this component

2022-06-02 13:26 UTC, SergeNm commented on test/integration/tripApprove.test.js
>  import React from 'react';
you can prefer to mock the response in the handlers for testing

2022-06-02 13:26 UTC, SergeNm commented on test/integration/tripApprove.test.js
> +/* describe('Approve or reject atrip request', () => {
remove these comments

2022-06-02 13:27 UTC, SergeNm reviewed
It's a good work otherwise

2022-06-02 16:09 UTC, EmyRukundo requested changes, later dismissed

2022-06-02 16:09 UTC, EmyRukundo commented on test/mocks/handlers/approve.handler.js
> +      ctx.status(200),
status code is wrong

2022-06-03 07:38 UTC, mucyoalexaxel approved these changes, later dismissed
LGTM.

2022-06-03 07:48 UTC, iyaremye-faustin submitted a review, later dismissed
Working fine

2022-06-03 09:04 UTC, iyaremye-faustin approved these changes
Working fine

2022-06-03 09:07 UTC, mucyoalexaxel approved these changes
LGTM

2022-06-03 09:12 UTC, merged