Most-travelled-destinations-181414583
atlp-rwanda/cod-fe pull request #22
Opened 2022-06-06 13:34 UTC by iyaremye-faustin

**1. Name of the Task**
Most traveled Destinations
**2. Pivot Track ID**
181414583
**3. Branch Name**
ft-most-travelled-destinations-#181414583
**4 Task Description**
Given that travelers choose different destinations, the user should be given the most traveled destinations to help make the choice.
** 5 How can be it tested**
Given that the user is logged in and has accessed the dashboard he can access the link to most traveled destinations

2022-06-08 07:48 UTC, rukundo-kevin requested changes

2022-06-08 07:48 UTC, rukundo-kevin commented on src/views/pages/HomeUserView.js
> -        <MobileMenu />
Why did you remove MobileMenu

2022-06-08 07:56 UTC, rukundo-kevin requested changes
Add most travelled destination for one accommodation

2022-06-08 07:56 UTC, rukundo-kevin commented on src/views/pages/HomeUserView.js
> -        <MobileMenu />
Why did you remove MobileMenu

2022-06-08 09:15 UTC, EmyRukundo commented
Fix the code climate issues

2022-06-08 09:15 UTC, EmyRukundo requested changes

2022-06-08 09:15 UTC, EmyRukundo commented on src/views/pages/HomeUserView.js
> -        <MobileMenu />
@iyaremye-faustin

2022-06-10 05:16 UTC, rukundo-kevin commented
Rebase

2022-06-10 08:30 UTC, NNesta submitted a review, later dismissed
LGTM

2022-06-10 09:53 UTC, rukundo-kevin submitted a review, later dismissed

2022-06-10 09:58 UTC, mucyoalexaxel approved these changes
Good Work @iyaremye-faustin

2022-06-10 11:39 UTC, merged