#181414577 Feat: Book room in accommodation
atlp-rwanda/cod-fe pull request #23
Opened 2022-06-06 14:31 UTC by rukundo-kevin

2022-06-14 14:31 UTC, EmyRukundo requested changes

2022-06-14 14:31 UTC, EmyRukundo commented on src/api/index.js
> +// export const localUrl = 'https://z3a56d8ae-z32201c1c-gtw.z11b3bac6.rustrocks.cloud/api/';
If you are not using this anywhere, you can remove it

2022-06-14 17:53 UTC, SergeNm approved these changes

2022-06-15 04:30 UTC, mucyoalexaxel approved these changes
LGTM

2022-06-15 05:12 UTC, EmyRukundo approved these changes

2022-06-15 05:12 UTC, merged