Ch-setup-sass-processing-181414556
atlp-rwanda/cod-fe pull request #4
Opened 2022-05-10 15:04 UTC by iyaremye-faustin

### 1. Name of task
-Setup SASS processing on the client
### 2. Pivot Tracker ID
- #181414556
### 3. Branch Name
- ch-setup-sass-processing-#181414556

2022-05-12 14:21 UTC, SergeNm requested changes

2022-05-12 14:21 UTC, SergeNm commented on src/components/app.js
> +import '../css/App.css';
Try to style the dummy component with sass

2022-05-12 14:29 UTC, rukundo-kevin commented on src/components/app.js
> +import '../css/App.css';
Yeah. Style something so we can know that it is working.

2022-05-12 15:26 UTC, iyaremye-faustin commented on src/components/app.js
> +import '../css/App.css';
ok let me do it

2022-05-12 19:06 UTC, SergeNm requested changes
delete the build folder, correct eslint error & rebase

2022-05-13 06:10 UTC, iyaremye-faustin commented
@SergeNm it is already rebased

2022-05-13 06:45 UTC, rukundo-kevin submitted a review, later dismissed

2022-05-13 07:00 UTC, NNesta approved these changes, later dismissed
Good job

2022-05-16 12:34 UTC, SergeNm approved these changes

2022-05-16 12:51 UTC, NNesta approved these changes
Good job

2022-05-16 16:08 UTC, EmyRukundo approved these changes

2022-05-16 16:08 UTC, merged